### ISSUE TITLE
When checking the ping, the application crashes

### ISSUE THREAD

**Issue by dukker11** [wanliyunyan/xray_ios#3]
When ping is pressed, the application freezes and crashes. What to do?

**Comment by wanliyunyan** [comment]
I just called LibXrayPing after xray was started, and the program crashed

**Comment by dukker11** [comment]
if you request a ping again, the application crashes

`2024/10/03 21:20:23 Reuse of exported var name: stats
2024/10/03 21:20:23 Reuse of exported var name: stats
panic: Reuse of exported var name: stats
	

goroutine 17 [running, locked to thread]:
log.Panicln({0x1300599d0?, 0x5?, 0x1303a4f80?})
	/opt/homebrew/Cellar/go/1.23.1/libexec/src/log/log.go:446 +0x60
expvar.Publish({0x1061f6604, 0x5}, {0x106706080, 0x1303a4f70})
	/opt/homebrew/Cellar/go/1.23.1/libexec/src/expvar/expvar.go:311 +0xbc
github.com/xtls/xray-core/app/metrics.NewMetricsHandler({0x1067150e8, 0x12b548f30}, 0x1301347c0)
	/Users/pan/go/pkg/mod/github.com/xtls/xray-core@v1.8.24/app/metrics/metrics.go:38 +0x10c
github.com/xtls/xray-core/app/metrics.init.1.func1({0x1067150e8?, 0x12b548f30?}, {0x1065cef20?, 0x1301347c0?})
	/Users/pan/go/pkg/mod/github.com/xtls/xray-core@v1.8.24/app/metrics/metrics.go:117 +0x40
github.com/xtls/xray-core/common.CreateObject({0x1067150e8, 0x12b548f30}, {0x1065cef20, 0x1301347c0})
	/Users/pan/go/pkg/mod/github.com/xtls/xray-core@v1.8.24/common/type.go:32 +0x148
github.com/xtls/xray-core/core.CreateObject(0x1301dabe0?, {0x1065cef20?, 0x1301347c0?})
	/Users/pan/go/pkg/mod/github.com/xtls/xray-core@v1.8.24/core/functions.go:21 +0x68
github.com/xtls/xray-core/core.initInstanceWithConfig(0x13027eb40, 0x1301db3b0)
	/Users/pan/go/pkg/mod/github.com/xtls/xray-core@v1.8.24/core/xray.go:200 +0x23c
github.com/xtls/xray-core/core.New(0x13027eb40)
	/Users/pan/go/pkg/mod/github.com/xtls/xray-core@v1.8.24/core/xray.go:165 +0x50
github.com/xtls/libxray/xray.StartXray({0x130052660, 0x5f})
	/Users/pan/xrayGo/libXray/xray/xray.go:24 +0x88
github.com/xtls/libxray/xray.Ping({0x0?, 0xcb?}, {0x130052660, 0x5f}, 0x1e, {0x1303cc018, 0x16}, {0x1303cc000, 0x18})
	/Users/pan/xrayGo/libXray/xray/ping.go:15 +0x78
github.com/xtls/libxray.Ping({0x12b508000?, 0x110?})
	/Users/pan/xrayGo/libXray/xray_wrapper.go:54 +0xd4
main.proxylibXray__Ping({0x125d16080, 0x110, {0x0, 0x0, 0x0, 0x0}})
	/private/var/folders/5s/87f50tbn7lx74t9vdb75l4440000gn/T/gomobile-work-2592949271/ios/src-arm64/gobind/go_libXraymain.go:68 +0x2c`

**Comment by wanliyunyan** [comment]
@dukker11 
Yes, I don’t know why. I plan to ask what the reason is at https://github.com/XTLS/libXray,

**Comment by wanliyunyan** [comment]
@dukker11 Based on this [issue](https://github.com/XTLS/libXray/issues/43), do you have any good solutions?

**Comment by dukker11** [comment]
replace metrics with api

```
{
  "routing" : {
    "domainStrategy" : "IpIfNonMatch",
    "rules" : [
      {
        "inboundTag" : [
          "metricsIn"
        ],
        "type" : "field",
        "outboundTag" : "metricsOut"
      }
    ]
  },
  "inbounds" : [
    {
      "settings" : {
        "udp" : true,
        "auth" : "noauth"
      },
      "tag" : "socks",
      "protocol" : "socks",
      "listen" : "127.0.0.1",
      "port" : 59243
    },
    {
      "listen" : "127.0.0.1",
      "port" : 59244,
      "tag" : "metricsIn",
      "protocol" : "dokodemo-door",
      "settings" : {
        "address" : "127.0.0.1"
      }
    }
  ],
  "metrics" : {
    "tag" : "metricsOut"
  },
  "policy" : {
    "system" : {
      "statsInboundDownlink" : true,
      "statsOutboundDownlink" : true,
      "statsInboundUplink" : true,
      "statsOutboundUplink" : true
    }
  },
  "outbounds" : [
    {
      "protocol" : "vmess",
      "name" : "🇺🇸US | 🟢 | vmess | @oneclickvpnkeys | 3",
      "settings" : {
        "vnext" : [
          {
            "address" : "zula.ir",
            "users" : [
              {
                "id" : "950db6aa-4926-4616-816e-ec0312dcb87b",
                "security" : "auto"
              }
            ],
            "port" : 443
          }
        ]
      },
      "streamSettings" : {
        "wsSettings" : {
          "path" : "\/linkws",
          "host" : "jahfkjha.cfd"
        },
        "security" : "tls",
        "tlsSettings" : {
          "serverName" : "jahfkjha.cfd"
        },
        "network" : "ws"
      }
    }
  ],
  "stats" : {

  }
}
```

replace

```
{
  "log": {},
  "inbounds": [
    {
      "settings": {
        "network": "tcp,udp",
        "ota": true,
        "method": "chacha20-ietf-poly1305",
        "level": 8,
        "udp": false,
        "password": "123456"
      },
      "protocol": "shadowsocks",
      "port": 10808,
      "tag": "socks5",
      "listen": "127.0.0.1"
    },
    {
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "userLevel": 8,
        "udp": true
      },
      "port": 1087,
      "tag": "directSocks",
      "listen": "127.0.0.1"
    },
    {
      "settings": {
        "address": "[::1]"
      },
      "protocol": "dokodemo-door",
      "port": 62789,
      "tag": "api",
      "listen": "[::1]"
    },
    {
      "settings": {
        "port": 53,
        "timeout": 10,
        "network": "tcp,udp",
        "address": "8.8.8.8",
        "userLevel": 0
      },
      "port": 62790,
      "tag": "inDns",
      "protocol": "dokodemo-door",
      "listen": "127.0.0.1"
    }
  ],
  "outbounds": [
    {
      "streamSettings": {
        "security": "tls",
        "network": "ws",
        "wsSettings": {
          "headers": {
            "host": "VPnerOr.sajAdHaDaDI.WEbSITe"
          },
          "path": "/eOwMtmADY6cWup8R?ed=2560"
        },
        "tlsSettings": {
          "serverName": "vpNeRor.SAjadHADadi.WEbsiTe",
          "allowInsecure": false,
          "alpn": [],
          "fingerprint": "chrome"
        }
      },
      "settings": {
        "vnext": [
          {
            "users": [
              {
                "level": 0,
                "flow": "",
                "id": "b41e1631-ceb3-47c9-ba87-c65a46f2f5a8",
                "email": "",
                "encryption": "none"
              }
            ],
            "address": "www.speedtest.net",
            "port": 2096
          }
        ]
      },
      "protocol": "vless",
      "mux": {
        "enabled": false,
        "xudpConcurrency": 128,
        "concurrency": 50,
        "xudpProxyUDP443": "allow"
      },
      "tag": "proxy"
    },
    {
      "settings": {
        "fragment": {
          "interval": "10-100",
          "packets": "tlshello",
          "length": "80-250"
        },
        "userLevel": 8
      },
      "protocol": "freedom",
      "streamSettings": {
        "sockopt": {
          "tcpNoDelay": true
        }
      },
      "tag": "fragment"
    }
  ],
  "api": {
    "services": [
      "StatsService"
    ],
    "tag": "api"
  },
  "dns": {
    "disableFallbackIfMatch": true,
    "servers": [
      {
        "address": "8.8.8.8",
        "skipFallback": false
      }
    ],
    "tag": "dnsQuery",
    "disableFallback": true,
    "queryStrategy": "UseIP",
    "disableCache": true
  },
  "stats": {},
  "routing": {
    "domainStrategy": "AsIs",
    "balancers": [],
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "inboundTag": [
          "inDns"
        ],
        "outboundTag": "outDns",
        "type": "field"
      },
      {
        "inboundTag": [
          "dnsQuery"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "inboundTag": [
          "directSocks"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  },
  "policy": {
    "levels": {
      "8": {
        "statsUserUplink": false,
        "statsUserDownlink": false,
        "uplinkOnly": 1,
        "downlinkOnly": 1,
        "bufferSize": 0,
        "handshake": 4,
        "connIdle": 30
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsInboundDownlink": true,
      "statsOutboundDownlink": true,
      "statsInboundUplink": true
    }
  }
}
```

**Comment by wanliyunyan** [comment]
thank you
